# Etapa 1: Build da aplicação React
FROM node:18-alpine AS build

# Define o diretório de trabalho
WORKDIR /app

# Copia apenas os arquivos necessários para instalar dependências
COPY package.json yarn.lock ./

# Instala as dependências
RUN yarn install --frozen-lockfile

# Copia o restante do código para o diretório de trabalho
COPY . .

# Cria o build da aplicação React
RUN yarn build

# Etapa 2: Imagem final com Nginx
FROM nginx:1.23-alpine

# Copia os arquivos construídos da etapa de build para o diretório padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
