version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    depends_on:
      - api
